// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmwhipmonetbinddttos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imttd2hpcG1vbmV0YmluZGR0dG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0Nzc2NzQsImV4cCI6MjA4NzA1MzY3NH0.19KhM7INyEGyrFN6hdqiYI2dA1itcnBLe19JTFt_z5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});